name: Update microdata
on:
  schedule:
    - cron: '0 10 * * TUE'
jobs:
  update:
    name: update data
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main
        with:
          ref: main
          lfs: true
      - name: setup python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: install python and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r update/requirements.txt
      - name: run update script
        id: run_update_script
        run: |
          python update/update.microdata.py peru
          python update/update.microdata.py colombia
          python update/update.microdata.py argentina
          python update/update.microdata.py paraguay
          python update/update.microdata.py brazil
      - name: git status
        id: git-status
        run: |
          git config --global user.email "mauriforonda+socialdatos@gmail.com"
          git config --global user.name "sociedatosbot"
          echo ::set-output name=result::$(git status | tr -d "\n" | grep -c "nothing to commit")
      - name: commit
        if: steps.git-status.outputs.result == 0
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git pull
          git add -A
          git commit -m "[ci] actualizaci√≥n microdatos"
          git push -q "https://$GH_TOKEN@github.com/sociedatos/covid19-sudamerica-estadisticas.git" main
